
let borderframe = [
    // import Frame149 from '../../assets/Frame/Ellipse149.png';
    // import Frame152 from '../../assets/Frame/Ellipse152.png';
    // import Frame152 from '../../assets/Frame/Ellipse155.png';
    require('../../assets/Frame/Ellipse133.png'),
    require('../../assets/Frame/Ellipse134.png'),
    require('../../assets/Frame/Ellipse135.png'),
    require('../../assets/Frame/Ellipse136.png'),
    require('../../assets/Frame/Ellipse137.png'),
    require('../../assets/Frame/Ellipse138.png'),
    require('../../assets/Frame/Ellipse139.png'),
    require('../../assets/Frame/Ellipse140.png'),
    require('../../assets/Frame/Ellipse141.png'),
    require('../../assets/Frame/Ellipse142.png'),
    require('../../assets/Frame/Ellipse143.png'),
    require('../../assets/Frame/Ellipse144.png'),
    require('../../assets/Frame/Ellipse145.png'),
    require('../../assets/Frame/Ellipse146.png'),
    require('../../assets/Frame/Ellipse147.png'),
    require('../../assets/Frame/Ellipse148.png'),
    require('../../assets/Frame/Ellipse150.png'),
    require('../../assets/Frame/Ellipse151.png'),
    require('../../assets/Frame/Ellipse153.png'),
    require('../../assets/Frame/Ellipse154.png'),
    require('../../assets/Frame/Ellipse156.png'),
    require('../../assets/Frame/Ellipse157.png'),
    require('../../assets/Frame/Ellipse158.png'),
    require('../../assets/Frame/Ellipse159.png'),
    require('../../assets/Frame/Ellipse160.png'),
    require('../../assets/Frame/Ellipse161.png'),
    require('../../assets/Frame/Ellipse162.png'),
    require('../../assets/Frame/Ellipse163.png'),
    require('../../assets/Frame/Ellipse164.png'),
    require('../../assets/Frame/Ellipse165.png'),
    require('../../assets/Frame/Ellipse166.png'),
    require('../../assets/Frame/Ellipse167.png'),
    require('../../assets/Frame/Ellipse168.png'),
    require('../../assets/Frame/Ellipse169.png'),
    require('../../assets/Frame/Ellipse170.png'),
    require('../../assets/Frame/Ellipse171.png'),
    require('../../assets/Frame/Ellipse172.png'),
    require('../../assets/Frame/Ellipse173.png'),
    require('../../assets/Frame/Ellipse174.png'),
    require('../../assets/Frame/Ellipse175.png'),
    require('../../assets/Frame/Ellipse176.png'),
    require('../../assets/Frame/Ellipse177.png'),
    require('../../assets/Frame/Ellipse178.png'),
    require('../../assets/Frame/Ellipse179.png'),
    require('../../assets/Frame/Ellipse180.png'),
    require('../../assets/Frame/Ellipse181.png'),
    require('../../assets/Frame/Ellipse182.png'),
    require('../../assets/Frame/Ellipse183.png'),
    require('../../assets/Frame/Ellipse184.png'),
    require('../../assets/Frame/Ellipse185.png'),
    require('../../assets/Frame/Ellipse186.png'),
    require('../../assets/Frame/Ellipse187.png'),
    require('../../assets/Frame/Ellipse188.png'),
    require('../../assets/Frame/Ellipse189.png'),
    require('../../assets/Frame/Ellipse190.png'),
    require('../../assets/Frame/Ellipse191.png'),
    require('../../assets/Frame/Ellipse192.png'),
    require('../../assets/Frame/Ellipse193.png'),
    require('../../assets/Frame/Ellipse194.png'),
    require('../../assets/Frame/Ellipse195.png'),
    require('../../assets/Frame/Ellipse196.png'),
    require('../../assets/Frame/Ellipse197.png'),
    require('../../assets/Frame/Ellipse198.png'),
    require('../../assets/Frame/Ellipse199.png'),
    require('../../assets/Frame/Ellipse200.png'),
]

export default borderframe;



