
let borderframe = [
    // im Frame149 from '../Frame/Ellipse149.png';
    // import Frame152 from '../Frame/Ellipse152.png';
    // import Frame152 from '../Frame/Ellipse155.png';
    // require('../Frame/Ellipse133.png'),
    require('../Frame/Ellipse134.png'),
    require('../Frame/Ellipse135.png'),
    require('../Frame/Ellipse136.png'),
    require('../Frame/Ellipse137.png'),
    require('../Frame/Ellipse138.png'),
    require('../Frame/Ellipse139.png'),
    require('../Frame/Ellipse140.png'),
    require('../Frame/Ellipse141.png'),
    require('../Frame/Ellipse142.png'),
    require('../Frame/Ellipse143.png'),
    require('../Frame/Ellipse144.png'),
    require('../Frame/Ellipse145.png'),
    require('../Frame/Ellipse146.png'),
    require('../Frame/Ellipse147.png'),
    require('../Frame/Ellipse148.png'),
    require('../Frame/Ellipse150.png'),
    require('../Frame/Ellipse151.png'),
    require('../Frame/Ellipse153.png'),
    require('../Frame/Ellipse154.png'),
    require('../Frame/Ellipse156.png'),
    require('../Frame/Ellipse157.png'),
    require('../Frame/Ellipse158.png'),
    require('../Frame/Ellipse159.png'),
    require('../Frame/Ellipse160.png'),
    require('../Frame/Ellipse161.png'),
    require('../Frame/Ellipse162.png'),
    require('../Frame/Ellipse163.png'),
    require('../Frame/Ellipse164.png'),
    require('../Frame/Ellipse165.png'),
    require('../Frame/Ellipse166.png'),
    require('../Frame/Ellipse167.png'),
    require('../Frame/Ellipse168.png'),
    require('../Frame/Ellipse169.png'),
    require('../Frame/Ellipse170.png'),
    require('../Frame/Ellipse171.png'),
    require('../Frame/Ellipse172.png'),
    require('../Frame/Ellipse173.png'),
    require('../Frame/Ellipse174.png'),
    require('../Frame/Ellipse175.png'),
    require('../Frame/Ellipse176.png'),
    require('../Frame/Ellipse177.png'),
    require('../Frame/Ellipse178.png'),
    require('../Frame/Ellipse179.png'),
    require('../Frame/Ellipse180.png'),
    require('../Frame/Ellipse181.png'),
    require('../Frame/Ellipse182.png'),
    require('../Frame/Ellipse183.png'),
    require('../Frame/Ellipse184.png'),
    require('../Frame/Ellipse185.png'),
    require('../Frame/Ellipse186.png'),
    require('../Frame/Ellipse187.png'),
    require('../Frame/Ellipse188.png'),
    require('../Frame/Ellipse189.png'),
    require('../Frame/Ellipse190.png'),
    require('../Frame/Ellipse191.png'),
    require('../Frame/Ellipse192.png'),
    require('../Frame/Ellipse193.png'),
    require('../Frame/Ellipse194.png'),
    require('../Frame/Ellipse195.png'),
    require('../Frame/Ellipse196.png'),
    require('../Frame/Ellipse197.png'),
    require('../Frame/Ellipse198.png'),
    require('../Frame/Ellipse199.png'),
    require('../Frame/Ellipse200.png'),
]

export default borderframe;



